config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :convoys do
    resources :favorite_convoys, only: [:create]
    resources :members, only: :create
    resources :reviews, only: :create
  end
  resources :users, only: [:index, :show, :edit, :update]
  resources :members, only: :destroy
  resources :favorite_convoys, only: :destroy

  get 'kitchensink', to: 'pages#kitchensink'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/convoy.rb
class Convoy < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  has_many :members
  has_many :favorite_convoys
  has_many :reviews
  belongs_to :user
  belongs_to :to_location, class_name: 'Location', optional: true
  belongs_to :from_location, class_name: 'Location', optional: true

  validates :name, :from_location_id, :to_location_id, presence: true

  def locations
    [from_location, to_location]
  end

  def features
    locations.map(&:to_feature)
  end

  def is_following?(user)
    FavoriteConvoy.find_by(user_id: user.id, convoy_id: id).present?
  end
end

app/models/favorite_convoy.rb
class FavoriteConvoy < ApplicationRecord
  belongs_to :convoy
end

app/models/location.rb
class Location < ApplicationRecord
  def convoys
    Convoy.where("to_location_id = #{id} OR from_location_id = #{id}")
  end

  def coordinates
    [longitude, latitude]
  end

  def to_feature
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": coordinates
      }
    }
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :convoy

  validates :convoy, uniqueness: { scope: :user }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :convoy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :photo, PhotoUploader

  has_many :members
  has_many :convoys
  has_many :favorite_convoys
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/convoys_controller.rb
class ConvoysController < ApplicationController
  before_action :set_convoy, only: %i[show update edit destroy]

  def index
    if params[:query].present?
      sql_query = "locations.name ILIKE :query \
        OR convoys.name ILIKE :query \
        OR users.name ILIKE :query \
      "
      @convoys = policy_scope(Convoy).joins(:user, :from_location, :to_location).where(sql_query, query: "%#{params[:query]}%")
    else
      @convoys = policy_scope(Convoy).all
    end
  end

  def show
    @member = Member.find_by(user_id: current_user.id, convoy_id: @convoy.id)
    @review = Review.new
    @able_to_join = @member ? false : true

    @geojson = build_geojson
  end

  def new
    @convoy = Convoy.new
    authorize @convoy
  end

  def create
    LocationService.new(params).create_location_hash
    @convoy = Convoy.new(convoy_params)
    authorize @convoy

    if @convoy.save
      redirect_to convoy_path(@convoy)
    else
      render :new
    end
  end

  def edit
    authorize @convoy
  end

  def update
    authorize @convoy
    @convoy.update(convoy_params)

    redirect_to convoy_path(@convoy)
  end

  def destroy
    authorize @convoy
    @convoy.delete

    redirect_to convoys_path
  end

  private

  def build_geojson
    {
      type: "FeatureCollection",
      features: @convoy.features
    }
  end

  def set_convoy
    @convoy = Convoy.find(params[:id])
    authorize @convoy
  end

  def convoy_params
    params.require(:convoy).permit(:from_location_id, :to_location_id, :name, :start_date, :finish_date,
                                   :fwd_only, :user_id, :completed, :photo)
  end
end

app/controllers/favorite_convoys_controller.rb
class FavoriteConvoysController < ApplicationController
  def create
    @convoy = Convoy.find(params[:convoy_id])
    @favorite_convoy = FavoriteConvoy.new(convoy_id: params[:convoy_id], user_id: current_user.id)
    authorize @favorite_convoy

    @favorite_convoy.save
    respond_to do |format|
      format.html { redirect_to convoys_path }
      format.js
    end
  end

  def destroy
    @favorite_convoy = FavoriteConvoy.find(params[:id])
    @convoy = @favorite_convoy.convoy

    authorize @favorite_convoy

    @favorite_convoy.delete

    respond_to do |format|
      format.html { redirect_to convoys_path }
      format.js { render :create }
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def create
    @convoy = Convoy.find(params[:convoy_id])
    @member = Member.new(user_id: current_user.id, convoy_id: @convoy.id)
    authorize @member

    if @member.save
      respond_to do |format|
        format.html { redirect_to convoy_path(@convoy) }
        format.js  # <-- will render `app/views/members/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'convoys/show' }
        format.js
      end
    end
    # redirect_to convoy_path(@convoy)
  end

  def destroy
    @convoy = Convoy.find(params[:id])
    member = Member.find_by(user_id: current_user.id, convoy_id: @convoy.id)
    authorize member
    member.destroy

    redirect_to convoy_path(@convoy)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @convoy = Convoy.find(params[:convoy_id])
    @review = Review.new(review_params)
    authorize @review
    @review.convoy = @convoy

    if @review.save
      respond_to do |format|
        format.html { redirect_to convoy_path(@convoy) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'convoys/show' }
        format.js
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def index
    @users = policy_scope(User).all
  end

  def show
  end

  def edit
  end

  def update
    @user.update(user_params)

    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = current_user
    authorize @user
  end

  def user_params
    params.require(:user).permit(:email, :country, :phone_number, :active, :age, :name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/convoys/_convoy_card.html.erb
<p>Name: <%= @convoy.name %></p>
<p>Start from: <%= @convoy.from_location.name %></p>
<p>Finish at: <%= @convoy.to_location.name %></p>
<p>This convoy has currently <strong><%=@convoy.members.count%> members</strong></p>

<% if @convoy.user_id == current_user.id %>
  <p> <%= link_to 'Delete', convoy_path(@convoy), method: :delete, data: { confirm: "Are you sure?" } %></p>
  <p><%= link_to 'Edit the trip', edit_convoy_path(@convoy) %></p>
<% else %>
  <% if @able_to_join %>
    <p><%= link_to 'Join Convoy!', convoy_members_path(@convoy), method: :post, remote: true, class: 'btn btn-black', id: "sweet-alert-demo" %></p>
  <% else %>
    <p>You are part of this convoy!</p> <%= link_to 'Remove', member_path(@convoy), method: :delete, class: 'btn btn-black', data: { confirm: 'Sure?' } %>
  <% end %>
<% end %>

app/views/convoys/_form.html.erb
<div class="form">
  <%= simple_form_for @convoy  do |f| %>
    <%= f.hidden_field  :user_id, value: current_user.id  %>
    <%= f.input :name, label: "Make up a cool name for your convoy" %>
    <%= f.input :fwd_only, label: "Is it only suitable for 4WD's?" %>
    <%= f.input :start_date, as: :string, label: "When do you want to depart?", input_html: { class: "datepicker" }  %>
    <%= f.input :finish_date, as: :string, label: "When will you arrive?", input_html: { class: "datepicker" } %>
    <%= f.input :to_location, as: :string, label: "To location", input_html: { value: @convoy&.to_location&.name } %>
    <%= f.input :from_location, as: :string, label: "From location", input_html: { value: @convoy&.from_location&.name } %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.button :submit, class: 'btn-black' %>
  <% end %>
</div>

app/views/convoys/_heart.html.erb
<% if convoy.is_following?(current_user) %>
  <%= link_to favorite_convoy_path(FavoriteConvoy.find_by(user_id: current_user.id, convoy_id: convoy.id)), method: :delete, remote: true do %>
    <i class="fas fa-heart favorite_convoy_heart"></i>
  <% end %>
<% else %>
  <%= link_to convoy_favorite_convoys_path(convoy), method: :post, remote: true do %>
    <i class="far fa-heart favorite_convoy_heart"></i>
  <% end %>
<% end %>

app/views/convoys/create.html.erb
<h1>Convoys#create</h1>
<p>Find me in app/views/convoys/create.html.erb</p>

app/views/convoys/destroy.html.erb
<h1>Convoys#destroy</h1>
<p>Find me in app/views/convoys/destroy.html.erb</p>

app/views/convoys/edit.html.erb
<%= render 'form', convoy: @convoy %>

app/views/convoys/index.html.erb
<%= form_tag convoys_path, method: :get do %>
  <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Find a convoy" %>
<% end %>

<div class="container">
  <% @convoys.each do |convoy| %>
    <div class="card-kitchen">
      <div class="card__title">
        <p><%= convoy.name.upcase %></p>
      </div>
      <div data-convoy-id="<%= convoy.id %>" class="favorite_convoy_heart">
        <%= render 'heart', convoy: convoy %>
      </div>
      <div class="card__content">
        <div class="card__content-text">
          Members: <strong> <%= convoy.members&.count %> </strong><br>
          From: <strong> <%= convoy.from_location&.name %> </strong><br>
          To: <strong><%= convoy.to_location&.name %> </strong><br>
          FWD: <strong> <%= convoy.fwd_only %></strong><br>
          Start: <strong> <%= convoy.start_date&.strftime('%d-%m-%Y') %> </strong><br>
          <div class="card__links">
            <p><%= link_to 'Details', convoy_path(convoy) %></strong></p>
            <% if convoy.user_id == current_user.id %>
              <p><%= link_to 'Edit', edit_convoy_path(convoy) %></p>
              <p> <%= link_to 'Delete', convoy_path(convoy), method: :delete, data: { confirm: "Are you sure?" } %></p>
            <% end %>
          </div>
        </div>
        <div class="card__content-image">
          <%= cl_image_tag("https://images.unsplash.com/photo-1489993360877-883980cc7333?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=200&q=200",class: 'card__content-image-img') %>
        </div>
      </div>
    </div>
  <% end %>
</div>


<% if policy(Convoy).create? %>
  <%= link_to 'Start a convoy!', new_convoy_path, class: 'btn btn-success' %>
<% end %>

app/views/convoys/new.html.erb
<%= simple_form_for @convoy  do |f| %>
  <%= f.hidden_field  :user_id, value: current_user.id  %>
  <%= f.input :name, label: "Make up a cool name for your convoy" %>
  <%= f.input :fwd_only, label: "Is it only suitable for 4WD's?" %>
  <%= f.input :start_date, as: :date, label: "When do you want to depart?" %>
  <%= f.input :finish_date, as: :date, label: "When will you arrive?" %>
  <%= f.input :to_location, as: :string, label: "Will it work?" %>
  <%= f.button :submit, class: 'btn-danger' %>
<% end %>

app/views/convoys/show.html.erb
<div class="card">
  <div class="convoy-card-details">
    <div class="convoy-card-content" id='emieltest'>
      <%= render 'convoy_card' %>
    </div>
    <div id="hello-world">
    </div>
    <div class="convoy-card-map">
      <div id="new_map"
           style="height: 50vh; width: 50vh"
           data-convoys="<%= @geojson.to_json %>"
           data-convoy-id="<%= @convoy.id %>"
           data-mapbox-api-key=<%= ENV['MAPBOX_API_KEY'] %>>
      </div>
    </div>
  </div>
  <div class="btn btn-black", id="btn-form-dropdown">Add review!</div>
    <div class="form-wrapper form-hidden">
      <%= render 'reviews/form', convoy: @convoy, review: @review %>
  </div>
  <div id="reviews">
    <div class="reviews-count">
      <%= render 'reviews/reviewed' %>
    </div>
  </div>
</div>

app/views/convoys/update.html.erb
<h1>hello</h1>

app/views/favorite_convoys/create.js.erb
function renderUser(userHTML) {
  const convoy = document.querySelector("[data-convoy-id='<%= @convoy.id %>']");
  convoy.innerHTML = userHTML;
}

renderUser('<%= j render "convoys/heart", convoy: @convoy %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Convoyer!</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.50.0/mapbox-gl.css' rel='stylesheet' />
    <%= favicon_link_tag asset_path('finger.ico') %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div id="body-wrapper">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/members/create.html.erb
<h1>Members#create</h1>
<p>Find me in app/views/members/create.html.erb</p>

app/views/members/create.js.erb
const updateCard = (userData) => {
  const element = document.getElementById('emieltest');
  element.innerHTML = userData;
  element.insertAdjacentHTML('afterbegin', reviewHTML);
}

updateCard('<%= j render "convoys/convoy_card", convoy: @convoy, able_to_join: false %>');

app/views/pages/home.html.erb
<div class="background-banner">
  <div class="grouped-info">
    <span id='convoy-title'></span>
    <p>Create or join a convoy to team up on those long drives through the outback.</p>
    <%= link_to 'Start a convoy!', new_convoy_path, class: 'btn btn-black' %>
  </div>
</div>


<div class="home-explainer">
  <div class="grid1 explainer-white">
    <div class="find-convoy">
      <h4>Finding a convoy</h4>
      <p>1. Search for a route</p>
      <p>2. Apply to join convoy</p>
      <p>3. Wait for confirmation</p>
      <p>4. That's it, ready to go!</p>
    </div>
  </div>
  <div class="grid2 explainer-black">
    <img src="http://cubimension.net/blog/wp-content/uploads/2014/08/hitchhiker.jpg" class="explainer-image">
  </div>

  <div class="grid3 explainer-black">
    <img src="https://cdni.rt.com/files/2018.06/article/5b1cd990fc7e93b97f8b45bb.jpg" class="explainer-image">
  </div>
  <div class="grid4 explainer-white">
    <div class="create-convoy">
      <h4>Creating a convoy</h4>
      <p>1. Define your route</p>
      <p>2. Set your criteria</p>
      <p>3. Wait for people to join</p>
      <p>4. That's it, ready to go!</p>
    </div>
  </div>
</div>

<!-- <button id="sweet-alert-demo" class="btn btn-black">Click me!</button> -->

app/views/pages/kitchensink.html.erb
<h1>CARD INDEX</h1>

<div class="card-kitchen">
  <div class="card__title">
    <p>Placeholder</p>
  </div>
  <i class="far fa-heart favorite_convoy_heart"></i>
  <div class="card__content">
    <div class="card__content-text">
     Members: <br>
     From: <br>
     To: <br>
     FWD: <br>
     Start: <br>
    </div>
    <div class="card__content-image">
      <%= cl_image_tag("https://images.unsplash.com/photo-1489993360877-883980cc7333?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=200&q=200",class: 'card__content-image-img') %>
    </div>
  </div>
</div>


<h1>CARD SHOW</h1>

app/views/reviews/_form.html.erb
<div class="card">
  <%= simple_form_for([ convoy, review ], remote: true) do |form| %>
    <%= form.input :content %>
    <%= form.input :rating %>
    <%= form.button :submit, class: 'btn btn-black' %>
  <% end %>
</div>

app/views/reviews/_reviewed.html.erb
<h2>Reviews:</h2>
<% @convoy.reviews.order(:created_at).reverse.each do |review| %>
  <div class="card">
    <p> <%= review.content  %></p>
    <p><%= review.rating %></p>
  </div>
<% end %>

app/views/reviews/create.js.erb
function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('new_review');
  newReviewForm.innerHTML = innerHTML;
}

function addReview(reviewHTML) {
  const reviews = document.getElementById('reviews');
  reviews.innerHTML = null;
  reviews.insertAdjacentHTML('beforeend', reviewHTML);
}

<% if @review.errors.any? %>
  refreshForm('<%= j render "reviews/form", convoy: @convoy, review: @review %>');
<% else %>
  addReview('<%= j render "reviews/reviewed", convoy: @convoy %>');
  refreshForm('<%= j render "reviews/form", convoy: @convoy, review: Review.new %>');
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-banner" id="footer">
  <div class="footer-flex">
    <h2>Follow our social</h2>
    <div class="footer-social">
      <i class="fab fa-facebook-square fa-3x" id='emieltest'></i>
      <i class="fab fa-twitter-square fa-3x"></i>
      <i class="fab fa-google-plus-square fa-3x"></i>
      <i class="fab fa-youtube-square fa-3x"></i>
    </div>
    <div class="footer-coffee">
      <p> Or come have a coffee <i class="fas fa-heart red-heart"></i> </p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <i class="fas fa-home fa-2x"></i>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= render 'shared/user_avatar' %>
    </ul>
  </div>
</div>

app/views/shared/_user_avatar.html.erb
<% if user_signed_in? %>
  <li class="nav-item active explore">
    <%= link_to "Home", "/", class: "nav-link" %>
  </li>
  <li class="nav-item explore">
    <%= link_to "Explore", convoys_path, class: "nav-link" %>
  </li>
  <li class="nav-item dropdown">
    <% if current_user.photo %>
      <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% else %>
      <%= image_tag 'http://icons.iconarchive.com/icons/icons8/ios7/256/Users-User-Male-4-icon.png', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% end %>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
      <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
    </div>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to "Login", new_user_session_path, class: "nav-link" %>
  </li>
<% end %>

app/views/users/_user_form.html.erb
<div class="user-edit-form-custom">
  <%= simple_form_for(@user) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :email, required: true, autofocus: true %>

      <%= f.input :password,
                  hint: "leave it blank if you don't want to change it",
                  required: false,
                  input_html: { autocomplete: "new-password" } %>
      <%= f.input :password_confirmation,
                  required: false,
                  input_html: { autocomplete: "new-password" } %>

      <%= f.input :current_password,
                  hint: "we need your current password to confirm your changes",
                  required: true,
                  input_html: { autocomplete: "current-password" } %>

      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>

    </div>

    <div class="form-actions">
      <%= f.button :submit, "Update" %>
    </div>
  <% end %>

  <h3>Cancel my account</h3>

  <p>Unhappy? <%= link_to "Cancel my account", registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete %></p>

  <%= link_to "Back", :back %>

</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h3>All users that may have interesting convoys conming up</h3>

<% @users.each do |user| %>
  <div class="card">
    <%= user.name %>
    <%= user.email %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Hey there, welcome to your profile page!</h1>

<% @user.convoys.each do |convoy| %>
  <div class="card">
    <p>Name: <%= convoy.name%></p>
    <p>Start at: <%= convoy.start_date.strftime("%d-%m-%Y")%></p>
    <p>Arrive at: <%= convoy.finish_date.strftime("%d-%m-%Y")%></p>
    <p>4WD only: <%= convoy.fwd_only%></p>
    <p>Started by: <%= convoy.user.name%></p>
    <p>From: <%= convoy.from_location.name %></p>
    <p>To: <%=convoy.to_location.name  %></p>
    <p><%= link_to 'Details', convoy_path(convoy) %></p>
    <p><%= link_to 'Edit', edit_convoy_path(convoy) %></p>
    <p> <%= link_to 'Delete', convoy_path(convoy), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %></p>
  </div>
<% end %>

<div class="btn btn-black", id="btn-form-dropdown">
  Edit personal details
</div>

<div class="form-wrapper form-hidden">
  <%= render 'user_form' %>
</div>